### ISSUE TITLE
 scr metrics are not using correctly information about profiles and affiliation

### ISSUE THREAD

**Issue by sanacl** [VizGrimoire/GrimoireLib#62]
- the queries we use in order to get these two tables (see link below) are not using the profile table to get the user name (at least one of them)
- It seems we have a similar problem with affiliation, where we print the first one instead of the correct one

http://korma.wmflabs.org/browser/scr-contributors.html

More information at https://phabricator.wikimedia.org/T112527#1757945

**Comment by aklapper** [comment]
Ironically, custom http://korma.wmflabs.org/browser/top-contributors.html lists ALL affiliations and not just the first one.

**Comment by aklapper** [comment]
Trying with "Legoktm" / "Kunal Mehta" (183a6db7ba70e79b208ae9f0923048467e6480dc) both listed on http://korma.wmflabs.org/browser/scr-contributors.html though they are a single person/uidentity:

## Affiliations

All past and present affiliations for a user are listed on http://korma.wmflabs.org/browser/top-contributors.html because https://github.com/VizGrimoire/GrimoireLib/blob/master/vizgrimoire/People.py#L22 currently gets ALL affiliations:

`SELECT pro.uuid, pro.name, pro.email, cou.name as country, org.name as affiliation FROM profiles pro JOIN enrollments enr ON enr.uuid= pro.uuid JOIN organizations org ON org.id = enr.organization_id LEFT JOIN countries cou ON cou.code = pro.country_code WHERE pro.uuid="183a6db7ba70e79b208ae9f0923048467e6480dc";`

To only get the current affiliation the query would have to be something like

`SELECT pro.uuid, pro.name, pro.email, cou.name as country, org.name as affiliation FROM profiles pro JOIN enrollments enr ON enr.uuid= pro.uuid JOIN organizations org ON org.id = enr.organization_id LEFT JOIN countries cou ON cou.code = pro.country_code WHERE pro.uuid="183a6db7ba70e79b208ae9f0923048467e6480dc" AND enr.start <= date_format(NOW(),'%Y-%m-%d %H:%i:%s') AND enr.end >= date_format(NOW(),'%Y-%m-%d %H:%i:%s');`

Is that territory of the "q_orgs" queries in vizgrimoire/metrics/scr_metrics.py ?

## User name
`SELECT * FROM identities WHERE identities.uuid="183a6db7ba70e79b208ae9f0923048467e6480dc";`
lists random "name" and random "username" entries for a uidentity. There is no "username" column entry with the value "Kunal Mehta" so this is at least tracked down to taking a random value from the "name" column.

**Comment by sduenas** [comment]
@aklapper I think we should wait for @dicortazar to reply about this issue. He's one of the main developers of GrimoireLib, so he should know what it is going on.

**Comment by aklapper** [comment]
(I created downstream https://phabricator.wikimedia.org/T118169 to track this in our workboard - feel free to close once it's closed here in Github too.)
